### ISSUE TITLE
what license should be applied to the content?

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/workingdistributed.com#1]
Tentatively leaning towards [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) as that feels the best fit for the audience, but we can re-evaluate down the track

**Comment by ghuntley** [comment]
I agree. I recommend also getting a CLA in place in case you ever want to turn this into a book — which you should.

**Comment by shiftkey** [comment]
@ghuntley good idea - any prior art or GH integrations you think are worth looking into?

**Comment by shiftkey** [comment]
Moving CLA discussion into #2
